name: Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Clean workspace
        run: git clean -ffdx

      - name: Install required Python packages
        run: |
          n=0
          until [ $n -ge 5 ]
          do
            pip install -r requirements.txt && break
            n=$[$n+1]
            sleep 15
          done
        shell: bash

      - name: Verify Python executable
        run: which python

      - name: List installed packages
        run: pip freeze

      - name: Run Streamlit App
        run: |
          streamlit run streamlit_mnist_app.py
        shell: bash
